services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ihm_backend:${IHM_BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      IHM_BACKEND_HOST: 0.0.0.0
      IHM_BACKEND_DB_HOST: ihm_backend-db
      IHM_BACKEND_DB_PORT: 5432
      IHM_BACKEND_DB_USER: ihm_backend
      IHM_BACKEND_DB_PASS: ihm_backend
      IHM_BACKEND_DB_BASE: ihm_backend
      IHM_BACKEND_REDIS_HOST: ihm_backend-redis

  taskiq-worker:
    <<: *main_app
    labels: []
    command:
      - taskiq
      - worker
      - ihm_backend.tkq:broker

  db:
    image: postgres:16.3-bullseye
    hostname: ihm_backend-db
    environment:
      POSTGRES_PASSWORD: "ihm_backend"
      POSTGRES_USER: "ihm_backend"
      POSTGRES_DB: "ihm_backend"
    volumes:
      - ihm_backend-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U ihm_backend
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: ihm_backend:${IHM_BACKEND_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      IHM_BACKEND_DB_HOST: ihm_backend-db
      IHM_BACKEND_DB_PORT: 5432
      IHM_BACKEND_DB_USER: ihm_backend
      IHM_BACKEND_DB_PASS: ihm_backend
      IHM_BACKEND_DB_BASE: ihm_backend
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:latest
    hostname: "ihm_backend-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  ihm_backend-db-data:
    name: ihm_backend-db-data
