"""create Stall table.

Revision ID: 8a508b1c7a9a
Revises: f1e9b071d685
Create Date: 2025-10-19 12:03:32.181081

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a508b1c7a9a"
down_revision = "f1e9b071d685"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stall",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stall_name", sa.String(), nullable=False),
        sa.Column("operator_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stall")
    # ### end Alembic commands ###
