"""added unit field to raw materials table.

Revision ID: 2193b601f757
Revises: 990e61c655b6
Create Date: 2025-10-25 14:25:01.906973

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2193b601f757"
down_revision = "990e61c655b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_material_requests", sa.Column("unit", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_material_requests", "unit")
    # ### end Alembic commands ###
