"""created required tables.

Revision ID: 990e61c655b6
Revises: 8a508b1c7a9a
Create Date: 2025-10-22 13:59:52.522611

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "990e61c655b6"
down_revision = "8a508b1c7a9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compiled_orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("compiled_order_id", sa.UUID(), nullable=False),
        sa.Column("item_name", sa.String(), nullable=False),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("delivered_quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["compiled_order_id"],
            ["compiled_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_material_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stall_id", sa.UUID(), nullable=False),
        sa.Column("item_name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stall_id"],
            ["stall.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vendor_updates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("compiled_order_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("status_update", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["compiled_order_id"],
            ["compiled_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vendor_updates")
    op.drop_table("raw_material_requests")
    op.drop_table("orders")
    op.drop_table("compiled_orders")
    # ### end Alembic commands ###
