"""add role and created_at to user.

Revision ID: f1e9b071d685
Revises: 819cbf6e030b
Create Date: 2025-10-19 09:01:25.289288

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1e9b071d685"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    userrole_enum = sa.Enum("ADMIN", "STALL_OWNER", "VENDOR", name="userrole")
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column(
        "user",
        sa.Column(
            "role",
            userrole_enum,
            nullable=False,
            server_default="STALL_OWNER",
        ),
    )
    op.add_column(
        "user", 
        sa.Column("created_at", sa.DateTime(), nullable=True, server_default=sa.text("NOW()"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "created_at")
    op.drop_column("user", "role")
    # Drop the ENUM type
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
