"""add order traceability, low stock threshold, unique stall operator.

Revision ID: 8c8ad9833703
Revises: add_invoice_fields
Create Date: 2026-09-15 23:33:41.380213

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c8ad9833703"
down_revision = "add_invoice_fields"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory",
        sa.Column(
            "low_stock_threshold", sa.Numeric(precision=10, scale=2), nullable=False,
            server_default="5",
        ),
    )
    op.add_column("orders", sa.Column("stall_id", sa.UUID(), nullable=True))
    op.add_column(
        "orders",
        sa.Column(
            "kitchen",
            sa.Enum("ATK", "BTK", "QTK", "CRAFT", name="kitchen"),
            nullable=True,
        ),
    )
    op.add_column(
        "orders", sa.Column("raw_material_request_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        None, "orders", "raw_material_requests", ["raw_material_request_id"], ["id"],
    )
    op.create_foreign_key(None, "orders", "stall", ["stall_id"], ["id"])
    op.create_unique_constraint(None, "stall", ["operator_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stall", type_="unique")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "raw_material_request_id")
    op.drop_column("orders", "kitchen")
    op.drop_column("orders", "stall_id")
    op.drop_column("inventory", "low_stock_threshold")
    # ### end Alembic commands ###
