"""
Comprehensive item classification for IHM training kitchens.
Covers BTK, ATK, QTK, and Craft Kitchen requirements across all cuisines.
"""

# (item_name, unit, vendor_category)
INVENTORY_ITEMS = [

    # ─────────────────────────────────────────────────────────────
    # SEAFOOD
    # ─────────────────────────────────────────────────────────────

    # Fish
    ("Pomfret (Black)", "kg", "seafood"),
    ("Pomfret (White)", "kg", "seafood"),
    ("Pomfret (Silver)", "kg", "seafood"),
    ("Seer Fish (Surmai)", "kg", "seafood"),
    ("Tilapia", "kg", "seafood"),
    ("Sea Bass", "kg", "seafood"),
    ("Salmon", "kg", "seafood"),
    ("Sardines", "kg", "seafood"),
    ("Mackerel (Bangda)", "kg", "seafood"),
    ("Sole Fish", "kg", "seafood"),
    ("Tuna", "kg", "seafood"),
    ("Bombay Duck (Bombil)", "kg", "seafood"),
    ("Hilsa (Ilish)", "kg", "seafood"),
    ("Bhetki", "kg", "seafood"),
    ("Rohu", "kg", "seafood"),
    ("Catla", "kg", "seafood"),
    ("Red Snapper", "kg", "seafood"),
    ("Kingfish", "kg", "seafood"),
    ("Barramundi", "kg", "seafood"),
    ("Trout", "kg", "seafood"),
    ("Karimeen (Pearlspot)", "kg", "seafood"),
    ("Fish Fillets (Frozen)", "kg", "seafood"),
    ("Fish Steaks", "kg", "seafood"),

    # Crustaceans
    ("Prawns (Medium)", "kg", "seafood"),
    ("King Prawns", "kg", "seafood"),
    ("Tiger Prawns", "kg", "seafood"),
    ("Vannamei Shrimp", "kg", "seafood"),
    ("Lobster", "kg", "seafood"),
    ("Crabs (Whole)", "kg", "seafood"),
    ("Crab Meat", "kg", "seafood"),
    ("Crawfish", "kg", "seafood"),

    # Shellfish & Molluscs
    ("Clams (Teesrya)", "kg", "seafood"),
    ("Mussels", "kg", "seafood"),
    ("Oysters", "nos", "seafood"),
    ("Scallops", "kg", "seafood"),
    ("Squid (Calamari)", "kg", "seafood"),
    ("Octopus", "kg", "seafood"),
    ("Dried Prawns", "kg", "seafood"),

    # ─────────────────────────────────────────────────────────────
    # VEGETABLES & FRUITS
    # ─────────────────────────────────────────────────────────────

    # Leafy Greens
    ("Spinach (Palak)", "kg", "vegetables_fruits"),
    ("Fenugreek Leaves (Methi)", "kg", "vegetables_fruits"),
    ("Mustard Greens (Sarson)", "kg", "vegetables_fruits"),
    ("Lettuce (Iceberg)", "kg", "vegetables_fruits"),
    ("Lettuce (Romaine)", "kg", "vegetables_fruits"),
    ("Lettuce (Butterhead)", "kg", "vegetables_fruits"),
    ("Arugula (Rocket)", "kg", "vegetables_fruits"),
    ("Kale", "kg", "vegetables_fruits"),
    ("Cabbage (Green)", "kg", "vegetables_fruits"),
    ("Cabbage (Red)", "kg", "vegetables_fruits"),
    ("Coriander Leaves (Dhaniya)", "kg", "vegetables_fruits"),
    ("Mint (Pudina)", "kg", "vegetables_fruits"),
    ("Curry Leaves (Kadi Patta)", "kg", "vegetables_fruits"),
    ("Basil", "kg", "vegetables_fruits"),
    ("Parsley", "kg", "vegetables_fruits"),
    ("Dill", "kg", "vegetables_fruits"),
    ("Thyme", "kg", "vegetables_fruits"),
    ("Rosemary", "kg", "vegetables_fruits"),
    ("Chives", "kg", "vegetables_fruits"),
    ("Tarragon", "kg", "vegetables_fruits"),

    # Roots & Tubers
    ("Potatoes", "kg", "vegetables_fruits"),
    ("Sweet Potato (Shakarkand)", "kg", "vegetables_fruits"),
    ("Carrots (Gajar)", "kg", "vegetables_fruits"),
    ("Onions (Red)", "kg", "vegetables_fruits"),
    ("Onions (White)", "kg", "vegetables_fruits"),
    ("Garlic (Lahsun)", "kg", "vegetables_fruits"),
    ("Ginger (Adrak)", "kg", "vegetables_fruits"),
    ("Beetroot (Chukandar)", "kg", "vegetables_fruits"),
    ("Radish (Mooli)", "kg", "vegetables_fruits"),
    ("Turnip (Shalgam)", "kg", "vegetables_fruits"),
    ("Yam (Ratalu)", "kg", "vegetables_fruits"),
    ("Taro Root (Arbi)", "kg", "vegetables_fruits"),
    ("Shallots", "kg", "vegetables_fruits"),
    ("Leeks", "kg", "vegetables_fruits"),
    ("Spring Onions", "kg", "vegetables_fruits"),
    ("Celery", "kg", "vegetables_fruits"),
    ("Parsnip", "kg", "vegetables_fruits"),

    # Cruciferous
    ("Broccoli", "kg", "vegetables_fruits"),
    ("Cauliflower (Phool Gobhi)", "kg", "vegetables_fruits"),
    ("Brussels Sprouts", "kg", "vegetables_fruits"),
    ("Kohlrabi (Nol Khol)", "kg", "vegetables_fruits"),

    # Gourds & Squashes
    ("Zucchini (Courgette)", "kg", "vegetables_fruits"),
    ("Bottle Gourd (Lauki)", "kg", "vegetables_fruits"),
    ("Ridge Gourd (Turai)", "kg", "vegetables_fruits"),
    ("Snake Gourd (Parwal)", "kg", "vegetables_fruits"),
    ("Pumpkin (Kaddu)", "kg", "vegetables_fruits"),
    ("Bitter Gourd (Karela)", "kg", "vegetables_fruits"),
    ("Okra (Bhindi)", "kg", "vegetables_fruits"),
    ("Cucumber (Khira)", "kg", "vegetables_fruits"),
    ("Ash Gourd", "kg", "vegetables_fruits"),

    # Nightshades
    ("Tomatoes", "kg", "vegetables_fruits"),
    ("Cherry Tomatoes", "kg", "vegetables_fruits"),
    ("Bell Pepper (Red)", "kg", "vegetables_fruits"),
    ("Bell Pepper (Green)", "kg", "vegetables_fruits"),
    ("Bell Pepper (Yellow)", "kg", "vegetables_fruits"),
    ("Green Chillies", "kg", "vegetables_fruits"),
    ("Red Chillies (Fresh)", "kg", "vegetables_fruits"),
    ("Brinjal / Eggplant (Baingan)", "kg", "vegetables_fruits"),

    # Legume Vegetables
    ("Green Peas (Matar)", "kg", "vegetables_fruits"),
    ("French Beans", "kg", "vegetables_fruits"),
    ("Runner Beans", "kg", "vegetables_fruits"),
    ("Broad Beans (Papdi)", "kg", "vegetables_fruits"),

    # Other Vegetables
    ("Sweet Corn", "kg", "vegetables_fruits"),
    ("Baby Corn", "kg", "vegetables_fruits"),
    ("Mushrooms (Button)", "kg", "vegetables_fruits"),
    ("Mushrooms (Portobello)", "kg", "vegetables_fruits"),
    ("Mushrooms (Oyster)", "kg", "vegetables_fruits"),
    ("Mushrooms (Shiitake)", "kg", "vegetables_fruits"),
    ("Asparagus", "kg", "vegetables_fruits"),
    ("Artichoke", "kg", "vegetables_fruits"),
    ("Fennel", "kg", "vegetables_fruits"),
    ("Bok Choy", "kg", "vegetables_fruits"),
    ("Lotus Stem (Kamal Kakdi)", "kg", "vegetables_fruits"),
    ("Drumstick (Sahjan)", "kg", "vegetables_fruits"),
    ("Raw Banana", "kg", "vegetables_fruits"),
    ("Raw Papaya", "kg", "vegetables_fruits"),
    ("Jackfruit (Raw)", "kg", "vegetables_fruits"),

    # Citrus Fruits
    ("Lemon (Nimbu)", "kg", "vegetables_fruits"),
    ("Lime", "kg", "vegetables_fruits"),
    ("Orange (Santra)", "kg", "vegetables_fruits"),
    ("Mosambi (Sweet Lime)", "kg", "vegetables_fruits"),
    ("Grapefruit", "kg", "vegetables_fruits"),
    ("Pomelo", "kg", "vegetables_fruits"),

    # Tropical & Stone Fruits
    ("Mango (Alphonso)", "kg", "vegetables_fruits"),
    ("Mango (Kesar)", "kg", "vegetables_fruits"),
    ("Mango (Langra)", "kg", "vegetables_fruits"),
    ("Banana (Kela)", "kg", "vegetables_fruits"),
    ("Papaya (Ripe)", "kg", "vegetables_fruits"),
    ("Pineapple (Ananas)", "kg", "vegetables_fruits"),
    ("Coconut (Fresh)", "nos", "vegetables_fruits"),
    ("Guava (Amrood)", "kg", "vegetables_fruits"),
    ("Watermelon (Tarbooj)", "kg", "vegetables_fruits"),
    ("Muskmelon (Kharbooza)", "kg", "vegetables_fruits"),
    ("Lychee (Litchi)", "kg", "vegetables_fruits"),
    ("Dragon Fruit", "kg", "vegetables_fruits"),
    ("Kiwi", "kg", "vegetables_fruits"),

    # Temperate Fruits
    ("Apple (Seb)", "kg", "vegetables_fruits"),
    ("Pear (Nashpati)", "kg", "vegetables_fruits"),
    ("Peach", "kg", "vegetables_fruits"),
    ("Plum (Aloo Bukhara)", "kg", "vegetables_fruits"),
    ("Apricot (Fresh)", "kg", "vegetables_fruits"),
    ("Grapes (Green)", "kg", "vegetables_fruits"),
    ("Grapes (Black)", "kg", "vegetables_fruits"),
    ("Pomegranate (Anar)", "kg", "vegetables_fruits"),
    ("Strawberries", "kg", "vegetables_fruits"),
    ("Blueberries", "kg", "vegetables_fruits"),
    ("Raspberries", "kg", "vegetables_fruits"),

    # ─────────────────────────────────────────────────────────────
    # GENERAL PROVISIONS
    # ─────────────────────────────────────────────────────────────

    # Pulses & Lentils
    ("Toor Dal (Pigeon Peas)", "kg", "general_provisions"),
    ("Masoor Dal (Red Lentils)", "kg", "general_provisions"),
    ("Moong Dal (Split)", "kg", "general_provisions"),
    ("Whole Moong (Green Gram)", "kg", "general_provisions"),
    ("Urad Dal (Split)", "kg", "general_provisions"),
    ("Whole Urad (Black Gram)", "kg", "general_provisions"),
    ("Chana Dal", "kg", "general_provisions"),
    ("Kabuli Chana (Chickpeas)", "kg", "general_provisions"),
    ("Rajma (Kidney Beans)", "kg", "general_provisions"),
    ("Black-Eyed Peas (Lobia)", "kg", "general_provisions"),
    ("Dried Green Peas", "kg", "general_provisions"),
    ("Soya Chunks", "kg", "general_provisions"),

    # Rice & Grains
    ("Basmati Rice", "kg", "general_provisions"),
    ("Jasmine Rice", "kg", "general_provisions"),
    ("Brown Rice", "kg", "general_provisions"),
    ("Arborio Rice", "kg", "general_provisions"),
    ("Parboiled Rice", "kg", "general_provisions"),
    ("Poha (Flattened Rice)", "kg", "general_provisions"),
    ("Puffed Rice (Murmura)", "kg", "general_provisions"),
    ("Oats", "kg", "general_provisions"),
    ("Barley (Jau)", "kg", "general_provisions"),
    ("Millet (Bajra)", "kg", "general_provisions"),
    ("Sorghum (Jowar)", "kg", "general_provisions"),
    ("Vermicelli (Seviyan)", "kg", "general_provisions"),
    ("Sabudana (Sago)", "kg", "general_provisions"),

    # Flours
    ("Wheat Flour (Atta)", "kg", "general_provisions"),
    ("Maida (All-Purpose Flour)", "kg", "general_provisions"),
    ("Semolina (Suji)", "kg", "general_provisions"),
    ("Besan (Chickpea Flour)", "kg", "general_provisions"),
    ("Rice Flour", "kg", "general_provisions"),
    ("Cornmeal", "kg", "general_provisions"),
    ("Rye Flour", "kg", "general_provisions"),
    ("Bread Flour", "kg", "general_provisions"),
    ("Cake Flour", "kg", "general_provisions"),
    ("Whole Wheat Flour", "kg", "general_provisions"),
    ("Cornstarch", "kg", "general_provisions"),
    ("Arrowroot Powder", "kg", "general_provisions"),
    ("Tapioca Starch", "kg", "general_provisions"),

    # Pasta & Noodles
    ("Spaghetti", "kg", "general_provisions"),
    ("Penne", "kg", "general_provisions"),
    ("Macaroni", "kg", "general_provisions"),
    ("Fettuccine", "kg", "general_provisions"),
    ("Lasagne Sheets", "kg", "general_provisions"),
    ("Rigatoni", "kg", "general_provisions"),
    ("Farfalle", "kg", "general_provisions"),
    ("Egg Noodles", "kg", "general_provisions"),
    ("Rice Noodles", "kg", "general_provisions"),
    ("Glass Noodles", "kg", "general_provisions"),
    ("Instant Noodles", "pkt", "general_provisions"),
    ("Breadcrumbs (Regular)", "kg", "general_provisions"),
    ("Panko Breadcrumbs", "kg", "general_provisions"),

    # Spices
    ("Black Pepper (Whole)", "kg", "general_provisions"),
    ("Black Pepper (Powder)", "kg", "general_provisions"),
    ("White Pepper (Powder)", "kg", "general_provisions"),
    ("Turmeric Powder (Haldi)", "kg", "general_provisions"),
    ("Red Chilli Powder", "kg", "general_provisions"),
    ("Kashmiri Red Chilli Powder", "kg", "general_provisions"),
    ("Cayenne Pepper", "kg", "general_provisions"),
    ("Paprika", "kg", "general_provisions"),
    ("Cumin Seeds (Jeera)", "kg", "general_provisions"),
    ("Cumin Powder", "kg", "general_provisions"),
    ("Coriander Seeds (Dhaniya)", "kg", "general_provisions"),
    ("Coriander Powder", "kg", "general_provisions"),
    ("Garam Masala", "kg", "general_provisions"),
    ("Chaat Masala", "kg", "general_provisions"),
    ("Tandoori Masala", "kg", "general_provisions"),
    ("Sambar Powder", "kg", "general_provisions"),
    ("Rasam Powder", "kg", "general_provisions"),
    ("Asafoetida (Hing)", "g", "general_provisions"),
    ("Fenugreek Seeds (Methi Dana)", "kg", "general_provisions"),
    ("Fennel Seeds (Saunf)", "kg", "general_provisions"),
    ("Cardamom Green (Elaichi)", "kg", "general_provisions"),
    ("Cardamom Black (Kali Elaichi)", "kg", "general_provisions"),
    ("Cinnamon (Dalchini)", "kg", "general_provisions"),
    ("Cloves (Laung)", "kg", "general_provisions"),
    ("Bay Leaves (Tej Patta)", "kg", "general_provisions"),
    ("Nutmeg (Jaiphal)", "kg", "general_provisions"),
    ("Mace (Javitri)", "kg", "general_provisions"),
    ("Star Anise (Chakri Phool)", "kg", "general_provisions"),
    ("Allspice", "kg", "general_provisions"),
    ("Dried Mango Powder (Amchur)", "kg", "general_provisions"),
    ("Carom Seeds (Ajwain)", "kg", "general_provisions"),
    ("Sesame Seeds (Til)", "kg", "general_provisions"),
    ("Poppy Seeds (Khus Khus)", "kg", "general_provisions"),
    ("Mustard Seeds (Rai)", "kg", "general_provisions"),
    ("Nigella Seeds (Kalonji)", "kg", "general_provisions"),
    ("Dried Red Chillies (Whole)", "kg", "general_provisions"),
    ("Saffron (Kesar)", "g", "general_provisions"),
    ("Dried Fenugreek Leaves (Kasuri Methi)", "kg", "general_provisions"),
    ("Mixed Herbs", "kg", "general_provisions"),
    ("Italian Seasoning", "kg", "general_provisions"),
    ("Chinese Five Spice", "kg", "general_provisions"),
    ("Peri Peri Spice", "kg", "general_provisions"),
    ("Szechuan Pepper", "kg", "general_provisions"),
    ("Smoked Paprika", "kg", "general_provisions"),

    # Salt
    ("Table Salt", "kg", "general_provisions"),
    ("Rock Salt (Sendha Namak)", "kg", "general_provisions"),
    ("Sea Salt", "kg", "general_provisions"),
    ("Black Salt (Kala Namak)", "kg", "general_provisions"),

    # Oils & Fats
    ("Vegetable Oil (Refined)", "L", "general_provisions"),
    ("Sunflower Oil", "L", "general_provisions"),
    ("Mustard Oil", "L", "general_provisions"),
    ("Coconut Oil", "L", "general_provisions"),
    ("Sesame Oil", "L", "general_provisions"),
    ("Olive Oil (Extra Virgin)", "L", "general_provisions"),
    ("Olive Oil (Pure)", "L", "general_provisions"),
    ("Peanut Oil", "L", "general_provisions"),
    ("Ghee (Desi)", "kg", "general_provisions"),
    ("Butter (Salted)", "kg", "general_provisions"),
    ("Butter (Unsalted)", "kg", "general_provisions"),
    ("Margarine", "kg", "general_provisions"),
    ("Shortening (Vanaspati)", "kg", "general_provisions"),

    # Sugar & Sweeteners
    ("White Sugar", "kg", "general_provisions"),
    ("Brown Sugar", "kg", "general_provisions"),
    ("Jaggery (Gur)", "kg", "general_provisions"),
    ("Honey (Shahad)", "kg", "general_provisions"),
    ("Icing Sugar", "kg", "general_provisions"),
    ("Caster Sugar", "kg", "general_provisions"),
    ("Molasses", "kg", "general_provisions"),
    ("Corn Syrup", "L", "general_provisions"),
    ("Maple Syrup", "L", "general_provisions"),

    # Dairy
    ("Milk (Full Fat)", "L", "general_provisions"),
    ("Milk (Toned)", "L", "general_provisions"),
    ("Yogurt / Curd (Dahi)", "kg", "general_provisions"),
    ("Paneer", "kg", "general_provisions"),
    ("Cream (Heavy)", "L", "general_provisions"),
    ("Cream (Whipping)", "L", "general_provisions"),
    ("Condensed Milk", "kg", "general_provisions"),
    ("Evaporated Milk", "L", "general_provisions"),
    ("Milk Powder", "kg", "general_provisions"),
    ("Buttermilk (Chaas)", "L", "general_provisions"),
    ("Sour Cream", "kg", "general_provisions"),
    ("Mozzarella Cheese", "kg", "general_provisions"),
    ("Cheddar Cheese", "kg", "general_provisions"),
    ("Parmesan Cheese", "kg", "general_provisions"),
    ("Cream Cheese", "kg", "general_provisions"),
    ("Processed Cheese", "kg", "general_provisions"),
    ("Feta Cheese", "kg", "general_provisions"),
    ("Mascarpone", "kg", "general_provisions"),
    ("Ricotta", "kg", "general_provisions"),

    # Eggs
    ("Eggs (Chicken)", "nos", "general_provisions"),
    ("Eggs (Duck)", "nos", "general_provisions"),
    ("Eggs (Quail)", "nos", "general_provisions"),

    # Meat & Poultry
    ("Chicken (Whole)", "kg", "general_provisions"),
    ("Chicken Breast", "kg", "general_provisions"),
    ("Chicken Thighs", "kg", "general_provisions"),
    ("Chicken Drumsticks", "kg", "general_provisions"),
    ("Chicken Wings", "kg", "general_provisions"),
    ("Chicken Mince (Keema)", "kg", "general_provisions"),
    ("Chicken Liver (Kaleji)", "kg", "general_provisions"),
    ("Mutton (Bone-in)", "kg", "general_provisions"),
    ("Mutton (Boneless)", "kg", "general_provisions"),
    ("Mutton Mince (Keema)", "kg", "general_provisions"),
    ("Mutton Liver", "kg", "general_provisions"),
    ("Mutton Kidney", "kg", "general_provisions"),
    ("Mutton Brain", "kg", "general_provisions"),
    ("Lamb Chops", "kg", "general_provisions"),
    ("Pork (Boneless)", "kg", "general_provisions"),
    ("Pork Chops", "kg", "general_provisions"),
    ("Pork Belly", "kg", "general_provisions"),
    ("Pork Mince", "kg", "general_provisions"),
    ("Beef (Boneless)", "kg", "general_provisions"),
    ("Beef Mince", "kg", "general_provisions"),
    ("Veal", "kg", "general_provisions"),
    ("Turkey", "kg", "general_provisions"),
    ("Duck", "kg", "general_provisions"),
    ("Quail", "nos", "general_provisions"),
    ("Ham", "kg", "general_provisions"),
    ("Bacon", "kg", "general_provisions"),
    ("Sausages (Pork)", "kg", "general_provisions"),
    ("Sausages (Chicken)", "kg", "general_provisions"),
    ("Salami", "kg", "general_provisions"),
    ("Pepperoni", "kg", "general_provisions"),

    # Condiments & Sauces
    ("White Vinegar", "L", "general_provisions"),
    ("Apple Cider Vinegar", "L", "general_provisions"),
    ("Malt Vinegar", "L", "general_provisions"),
    ("Balsamic Vinegar", "L", "general_provisions"),
    ("Soy Sauce", "L", "general_provisions"),
    ("Dark Soy Sauce", "L", "general_provisions"),
    ("Worcestershire Sauce", "L", "general_provisions"),
    ("Tomato Ketchup", "kg", "general_provisions"),
    ("Tomato Puree", "kg", "general_provisions"),
    ("Tomato Paste", "kg", "general_provisions"),
    ("Yellow Mustard", "kg", "general_provisions"),
    ("Dijon Mustard", "kg", "general_provisions"),
    ("Mustard Powder", "kg", "general_provisions"),
    ("Mayonnaise", "kg", "general_provisions"),
    ("Tamarind Paste (Imli)", "kg", "general_provisions"),
    ("Fish Sauce", "L", "general_provisions"),
    ("Oyster Sauce", "L", "general_provisions"),
    ("Hoisin Sauce", "L", "general_provisions"),
    ("Chilli Sauce", "L", "general_provisions"),
    ("Sriracha", "L", "general_provisions"),
    ("Tabasco", "L", "general_provisions"),
    ("Coconut Milk (Canned)", "L", "general_provisions"),
    ("Coconut Cream (Canned)", "L", "general_provisions"),
    ("Mango Pickle (Achar)", "kg", "general_provisions"),
    ("Mixed Vegetable Pickle", "kg", "general_provisions"),
    ("Capers", "kg", "general_provisions"),
    ("Olives (Green)", "kg", "general_provisions"),
    ("Olives (Black)", "kg", "general_provisions"),
    ("Anchovies", "kg", "general_provisions"),

    # Bakery Ingredients
    ("Baking Powder", "kg", "general_provisions"),
    ("Baking Soda (Meetha Soda)", "kg", "general_provisions"),
    ("Dry Active Yeast", "kg", "general_provisions"),
    ("Fresh Yeast", "kg", "general_provisions"),
    ("Vanilla Extract", "L", "general_provisions"),
    ("Vanilla Essence", "L", "general_provisions"),
    ("Almond Extract", "L", "general_provisions"),
    ("Cocoa Powder (Unsweetened)", "kg", "general_provisions"),
    ("Dark Chocolate", "kg", "general_provisions"),
    ("Milk Chocolate", "kg", "general_provisions"),
    ("White Chocolate", "kg", "general_provisions"),
    ("Chocolate Chips", "kg", "general_provisions"),
    ("Cocoa Butter", "kg", "general_provisions"),
    ("Food Colour (Red)", "ml", "general_provisions"),
    ("Food Colour (Green)", "ml", "general_provisions"),
    ("Food Colour (Yellow)", "ml", "general_provisions"),
    ("Food Colour (Blue)", "ml", "general_provisions"),
    ("Fondant (White)", "kg", "general_provisions"),
    ("Custard Powder", "kg", "general_provisions"),
    ("Gelatin (Powder)", "kg", "general_provisions"),
    ("Agar-Agar", "kg", "general_provisions"),
    ("Marzipan", "kg", "general_provisions"),
    ("Glucose Syrup", "kg", "general_provisions"),
    ("Cream of Tartar", "kg", "general_provisions"),
    ("Instant Pudding Mix", "kg", "general_provisions"),

    # Nuts & Dried Fruits
    ("Almonds (Badam)", "kg", "general_provisions"),
    ("Cashews (Kaju)", "kg", "general_provisions"),
    ("Walnuts (Akhrot)", "kg", "general_provisions"),
    ("Pistachios (Pista)", "kg", "general_provisions"),
    ("Peanuts (Moongphali)", "kg", "general_provisions"),
    ("Pine Nuts (Chilgoza)", "kg", "general_provisions"),
    ("Hazelnuts", "kg", "general_provisions"),
    ("Macadamia Nuts", "kg", "general_provisions"),
    ("Pecan Nuts", "kg", "general_provisions"),
    ("Coconut (Desiccated)", "kg", "general_provisions"),
    ("Raisins (Kishmish)", "kg", "general_provisions"),
    ("Dates (Dried / Khajoor)", "kg", "general_provisions"),
    ("Dried Apricots (Khubani)", "kg", "general_provisions"),
    ("Prunes", "kg", "general_provisions"),
    ("Dried Cranberries", "kg", "general_provisions"),
    ("Dried Figs (Anjeer)", "kg", "general_provisions"),
    ("Candied Peel", "kg", "general_provisions"),
    ("Candied Cherries", "kg", "general_provisions"),
    ("Sunflower Seeds", "kg", "general_provisions"),
    ("Pumpkin Seeds", "kg", "general_provisions"),
    ("Flax Seeds (Alsi)", "kg", "general_provisions"),
    ("Chia Seeds", "kg", "general_provisions"),

    # Beverages
    ("Tea Leaves (Chai)", "kg", "general_provisions"),
    ("Green Tea", "kg", "general_provisions"),
    ("Coffee (Ground)", "kg", "general_provisions"),
    ("Coffee Beans", "kg", "general_provisions"),
    ("Instant Coffee", "kg", "general_provisions"),
    ("Cocoa Drink Mix", "kg", "general_provisions"),
    ("Herbal Tea (Assorted)", "pkt", "general_provisions"),

    # Miscellaneous Provisions
    ("Cornflakes", "kg", "general_provisions"),
    ("Muesli", "kg", "general_provisions"),
    ("Bread (White Sliced)", "nos", "general_provisions"),
    ("Bread (Brown / Whole Wheat)", "nos", "general_provisions"),
    ("Pita Bread", "nos", "general_provisions"),
    ("Popcorn Kernels", "kg", "general_provisions"),
    ("Stock Cube (Chicken)", "nos", "general_provisions"),
    ("Stock Cube (Vegetable)", "nos", "general_provisions"),
    ("Tomato Sauce (Passata)", "L", "general_provisions"),
    ("Pesto Sauce", "kg", "general_provisions"),
    ("Tahini", "kg", "general_provisions"),
    ("Miso Paste", "kg", "general_provisions"),
    ("Wasabi Paste", "kg", "general_provisions"),
    ("Dried Mushrooms", "kg", "general_provisions"),
    ("Sun-Dried Tomatoes", "kg", "general_provisions"),
    ("Roasted Red Peppers (Canned)", "kg", "general_provisions"),
    ("Canned Tomatoes (Diced)", "kg", "general_provisions"),
    ("Canned Chickpeas", "kg", "general_provisions"),
    ("Canned Corn", "kg", "general_provisions"),
    ("Canned Tuna", "nos", "general_provisions"),
    ("Canned Sardines", "nos", "general_provisions"),
    ("Rose Water (Gulab Jal)", "L", "general_provisions"),
    ("Kewra Water", "L", "general_provisions"),
    ("Meethi Saunf (Sugar-Coated Fennel)", "kg", "general_provisions"),
    ("Silver Leaf (Chandi ka Vark)", "pkt", "general_provisions"),
    ("Sago (Sabudana)", "kg", "general_provisions"),
    ("Vermicelli (Rice)", "kg", "general_provisions"),
    ("Potato Starch", "kg", "general_provisions"),
    ("Liquid Glucose", "kg", "general_provisions"),
    ("Parchment Paper (Baking)", "roll", "general_provisions"),
    ("Cling Film", "roll", "general_provisions"),
    ("Aluminium Foil", "roll", "general_provisions"),
    ("Disposable Gloves", "box", "general_provisions"),
]

# Fast lookup dict: item_name.lower() → vendor_category
ITEM_CATEGORY_MAP: dict[str, str] = {
    name.lower(): cat for name, _unit, cat in INVENTORY_ITEMS
}
